language: rust
rust:
  - nightly
cache:
  yarn: true
  cargo: true
git:
  depth: 1
before_intall:
  - nvm install 8
  - export PATH=$HOME/.cargo/bin
install: bash ./ci/install.sh
script: cargo web test --target wasm32-unknown-unknown --nodejs
before_deploy: yarn run parcel build index.html --no-minify --public-url ./
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
